pipeline {
    agent any 
    stages {        
        stage("Permitions Configuration") {
            steps {
                sh "chmod -R 755 ../../scripts/"
                sh "chmod -R 755 ../../endpoints/"
            }
        }          
        stage("Create cluster Kubernetes") {
            steps {
                sh "../../scripts/commands/create-cluster.sh | bash"
            }
        }
    }
    post {
        always {
            echo "Executando retornos do job."
        }
        success {
            echo "Ambiente criado com sucesso!"
        }
        failure {
            echo "Erro ao criar ambiente. Consulte o log da console."
        }
        unstable {
            echo "Este build demonstra instabilidade"
        }
        changed {
            echo "Comandos alterados no pipeline... a verificar."
            echo "Builder em falha recuperado com sucesso!"
        }
    }
}